### PR TITLE
Reduce travis mail flood

### PR DESCRIPTION
**Pull request by dns2utf8**

### CODE REVIEW

**Review by dbrgn — APPROVED** [review]

**Comment by rnestler** [comment]
Can't you just change your travis settings? I don't receive such mail notifications.

**Comment by dbrgn** [comment]
https://docs.travis-ci.com/user/notifications/#Default-notification-settings

> By default, email notifications are sent to the committer and the commit author when they are members of the repository, that is they have
>
> - push or admin permissions for public repositories.
> - pull, push or admin permissions for private repositories.
>
> Emails are sent when, on the given branch:
>
> - a build was just broken or still is broken.
> - a previously broken build was just fixed.

**Comment by dns2utf8** [comment]
There are no settings on travis-ci.org so I will inform my spam filter to handle it 😉

**Comment by dbrgn** [comment]
I wonder where these mails are coming from...

**Comment by dns2utf8** [comment]
Me too. 🌈?

**Comment by dbrgn** [comment]
Why not…

**Pull request merged**
