### PR TITLE
Add link to deployed version

### PR DESCRIPTION
**Pull request by dbrgn**
I deployed it to https://validator.spacedirectory.org/v1/ :)

### CODE REVIEW

**Comment by rnestler** [comment]
> https://validator.spacedirectory.org/v1/

I get 502 Bad Gateway

**Comment by dbrgn** [comment]
Oh, the systemd unit file was missing the autorestart option. I'll fix it.

**Comment by dbrgn** [comment]
I started the service manually for now.

**Review by rnestler — APPROVED** [review]
LGTM. :shipit:

**Comment by dns2utf8** [comment]
It reverted to bad gateway again

**Comment by dbrgn** [comment]
Thanks for letting me know, it should be fixed for good now.

**Pull request merged**
