### PR TITLE
Raise limiter to over directory size

### PR DESCRIPTION
**Pull request by gidsi**
parallelizing calls for rebuilding the directory leads to problems, raising this to a number larger then the directory size should fix it

### CODE REVIEW

**Comment by dns2utf8** [comment]
A comment explainng.the magic numbers or using constants would be nice

**Comment by gidsi** [comment]
> A comment explainng.the magic numbers or using constants would be nice

Sure, if it helps you why not :)

**Review by dbrgn — APPROVED** [review]
Looks good to me.

**Comment by dns2utf8** [comment]
Thank you. I found the [explanation on the units in the go source code](https://github.com/golang/time/blob/master/rate/rate.go#L35-L38).

**Pull request merged**
